from pathlib import Path
from datetime import datetime

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill


class ExcelAgent:

    def generate_report(self, cases, advocate_name):

        # ----------------------------
        # Create Reports Folder
        # ----------------------------
        reports_folder = Path.cwd() / "reports"
        reports_folder.mkdir(parents=True, exist_ok=True)

        # ----------------------------
        # Workbook
        # ----------------------------
        wb = Workbook()
        ws = wb.active
        ws.title = "Cause List"

        # ----------------------------
        # Excel Headers
        # ----------------------------
        headers = [
            "S.No",
            "Court No",
            "Judge",
            "Cause List Date",
            "Hearing Time",
            "Stage / List",
            "Case Details",
            "IA Details",
            "Purpose / Petition",
            "Party",
            "Petitioner Advocate",
            "Respondent Advocate",
            "District",
        ]

        ws.append(headers)

        # ----------------------------
        # Header Style
        # ----------------------------
        blue_fill = PatternFill(
            start_color="4F81BD",
            end_color="4F81BD",
            fill_type="solid",
        )

        for cell in ws[1]:
            cell.font = Font(
                bold=True,
                color="FFFFFF"
            )
            cell.fill = blue_fill

        # ----------------------------
        # Insert Data
        # ----------------------------
        for case in cases:

            row = ws.max_row + 1

            # ----------------------------
            # Basic Case Information
            # ----------------------------

            ws.cell(
                row=row,
                column=1
            ).value = case["sno"]

            ws.cell(
                row=row,
                column=2
            ).value = case["court_no"]

            ws.cell(
                row=row,
                column=3
            ).value = case["judge"]

            ws.cell(
                row=row,
                column=4
            ).value = case["cause_list_date"]

            ws.cell(
                row=row,
                column=5
            ).value = case["hearing_time"]

            ws.cell(
                row=row,
                column=6
            ).value = case["stage"]

            # ----------------------------------------
            # Case Details Hyperlink
            # ----------------------------------------
            #
            # Example:
            #
            # Display:
            # WP/6079/2019
            #
            # Link:
            # https://aphc.gov.in/Hcdbs/
            # caseDetails1.jsp?casedet=WP/6079/2019
            #
            # ----------------------------------------

            case_cell = ws.cell(
                row=row,
                column=7
            )

            case_cell.value = case["case_details"]

            # Use the case_link generated by ExtractorAgent
            case_link = case.get("case_link")

            if case_link:

                case_cell.hyperlink = case_link

                # Excel's standard hyperlink appearance
                case_cell.style = "Hyperlink"

            # ----------------------------------------
            # Remaining Columns
            # ----------------------------------------

            ws.cell(
                row=row,
                column=8
            ).value = case["ia_details"]

            ws.cell(
                row=row,
                column=9
            ).value = case["purpose"]

            ws.cell(
                row=row,
                column=10
            ).value = case["party"]

            ws.cell(
                row=row,
                column=11
            ).value = case["pet_adv"]

            ws.cell(
                row=row,
                column=12
            ).value = case["res_adv"]

            ws.cell(
                row=row,
                column=13
            ).value = case["district"]

        # ----------------------------
        # Auto Width
        # ----------------------------
        for column in ws.columns:

            max_length = 0
            column_letter = column[0].column_letter

            for cell in column:

                try:

                    if cell.value:

                        max_length = max(
                            max_length,
                            len(str(cell.value))
                        )

                except Exception:

                    pass

            ws.column_dimensions[
                column_letter
            ].width = min(
                max_length + 5,
                50
            )

        # ----------------------------
        # Save Workbook
        # ----------------------------
        filename = (
            f"{advocate_name.replace(' ', '_')}_"
            f"{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
        )

        filepath = reports_folder / filename

        wb.save(filepath)

        print("\n" + "=" * 60)
        print("Excel saved successfully!")
        print(filepath.resolve())
        print("=" * 60)

        return filepath